package hbie2.nist.nativesdk;

/**
 * Created by pms on 2017/4/7.
 */
public enum SdkErrorCode {
    NO_ERRROR,
    ENCODE_ERROR,
    ENCODE_INIT_FAILED,
    ENCODE_TXT_NUMBER_ERROR,
    ENCODE_IMG_NUMBER_ERROR,
    ENCODE_TYPE1_DATA_ERROR,
    ENCODE_TYPE2_DATA_ERROR,
    ENCODE_TYPE4_DATA_ERROR,
    ENCODE_TYPE7_DATA_ERROR,
    ENCODE_TYPE8_DATA_ERROR,
    ENCODE_TYPE9_DATA_ERROR,
    ENCODE_TYPE10_DATA_ERROR,
    ENCODE_ADD_TRANSNO_ERROR,
    ENCODE_ADD_TXT_ERROR,
    ENCODE_ADD_IMAGE_ERROR,

    DECODE_INIT_FAILED,
    DECODE_TXT_NUMBER_ERROR,
    DECODE_IMG_NUMBER_ERROR,
    DECODE_ADD_IMAGE_FAILED,
    DECODE_ADD_TXT_FAILED,
    DECODE_TYPE1_DATA_ERROR,
    DECODE_TYPE2_DATA_ERROR,
    DECODE_TYPE4_DATA_ERROR,
    DECODE_TYPE7_DATA_ERROR,
    DECODE_TYPE8_DATA_ERROR,
    DECODE_TYPE9_DATA_ERROR,
    DECODE_TYPE10_DATA_ERROR,
    DECODE_ERROR,


}
